Algoritmo "AreaQuadrado"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Área de um Quadrado
// Autor(a)    : Einer Sulivan Mamani Choquetopa
// Data atual  : 18/09/2025

Var
   // Seção de Declarações das variáveis
   lado, area: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("")
   Escreval("Área de um Quadrado")
   Escreval("")
   Escreva("Digite o lado do quadrado: ")
   Escreval("")
   Leia(lado)
   area <- lado * lado
   Escreval("Área do quadrado =", area:0:2,".")
   Escreval("")

Fimalgoritmo