Algoritmo "Exercicio15Faccat"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calculo para descubrir se o numero e positivo ou negativo
// Autor(a)    : Einer Sulivan Mamani Choquetopa
// Data atual  : 17/09/2025


//Ler um valor e escrever se é positivo ou negativo
//(considere o valor zero como positivo).
Var
   // Seção de Declarações das variáveis
   num: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um numero: ")
   Leia(num)
   Escreval("")
   se num >= 0 entao
      Escreva("O numero e positivo")
   senao
      Escreva("O numero e negativo")
   fimse

Fimalgoritmo